version: '3'
services:
  jupyter:
    build:
      context: .
      dockerfile: dockerfile
    container_name: jupyter_test
    user: root
    environment:
      - GRANT_SUDO=yes
    ports:
      - "8888:8888"
    command: start-notebook.sh --NotebookApp.token=''
    volumes:
            - ./work:/home/jovyan/work/
  mysql:
    image: mysql
    container_name: mysql_test
    ports: 
       - "3306:3306"
    volumes:
       - ./mysql/data:/data/db/
    environment:
       MYSQL_ROOT_PASSWORD: cc10423
