version: '3'
services:
  jupyter:
    build:
      context: .
      dockerfile: dockerfile
    container_name: jupyter_test
    user: root
    environment:
      - GRANT_SUDO=yes
    ports:
      - "8888:8888"
    command: start-notebook.sh --NotebookApp.token=''
    volumes:
      - ./work:/home/user1/work/
  mariaDB:
    image: mariadb
    container_name: cc104.rds.local
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: cc10423
    ports:
      - "8889:8889"
    volumes:
      - ./mariadb/data:/data/db/
  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
